#!/bin/bash
### BEGIN INIT INFO
# Provides:          mysite
# Required-Start:    $syslog $remote_fs $network
# Required-Stop:     $syslog $remote_fs $network
# Should-Start:      fam
# Should-Stop:       fam
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start the mysite fcgi script.
### END INIT INFO

#PATH=/sbin:/bin:/usr/sbin:/usr/bin
NAME=nabludatel
DESC="nabludatel fcgi"
PIDFILE=/var/run/$NAME.pid
SCRIPTNAME=/etc/init.d/$NAME
SOCKET=/var/run/${NAME}.socket
DIR="/env-nabludatel/nabludatel"
ENV="/env-nabludatel/bin/activate"

#METHOD="prefork"
METHOD="threaded"

action=${1:-restart}

start() {
    cd ${DIR}
    source ${ENV}
    #python manage.py runfcgi method=${METHOD} socket=${SOCKET} pidfile=${PIDFILE} && echo "fcgi started."
    python manage.py runfcgi method=${METHOD} socket=${SOCKET} pidfile=${PIDFILE} && echo "fcgi started."
    chown www-data:www-data ${SOCKET}
}

stop() {
    if [ -e ${PIDFILE} ]
    then
        kill `cat ${PIDFILE}` && rm -f ${PIDFILE} &&  echo "fcgi stoped."
    fi
}

restart() {
    stop
    start
}

usage() {
echo "Arguments should be: start, stop, restart or None."
}

case ${action} in
    start   ) start   ;;
    stop    ) stop    ;;
    restart ) restart ;;
    *       ) usage   ;;
esac

